CONNECT SYS/Your_SYS_Password AS SYSDBA;

DROP PLUGGABLE DATABASE all_27493_octave_fdtms_db INCLUDING DATAFILES;

CREATE PLUGGABLE DATABASE all_27493_octave_fdtms_db
ADMIN USER fdtms_admin IDENTIFIED BY octave
CREATE_FILE_DEST = 'C:\APP\BOCTAVE\PRODUCT\23AI\ORADATA\FREE\';

ALTER PLUGGABLE DATABASE all_27493_octave_fdtms_db OPEN READ WRITE;
