CONNECT SYS/Your_SYS_Password@//localhost/all_27493_octave_fdtms_db AS SYSDBA;

 CREATE TABLESPACE FDTMS_DATA
DATAFILE 'fdtms_data01.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

CREATE TABLESPACE FDTMS_INDEX
DATAFILE 'fdtms_index01.dbf' SIZE 50M AUTOEXTEND ON NEXT 5M MAXSIZE 500M;

 CREATE USER FDTMS_TEMP_OCTAVE IDENTIFIED BY octave
DEFAULT TABLESPACE FDTMS_DATA
QUOTA UNLIMITED ON FDTMS_DATA;

 GRANT CONNECT TO FDTMS_TEMP_OCTAVE;
GRANT RESOURCE TO FDTMS_TEMP_OCTAVE; 
GRANT CREATE SESSION TO FDTMS_TEMP_OCTAVE;
GRANT CREATE TYPE TO FDTMS_TEMP_OCTAVE;
GRANT CREATE PROCEDURE TO FDTMS_TEMP_OCTAVE;
GRANT PDB_DBA TO FDTMS_TEMP_OCTAVE;
GRANT RESTRICTED SESSION TO FDTMS_TEMP_OCTAVE;

DISCONNECT;
